## There are two functions here :
## 1-makeCacheMatrix creates a special matrix that cache its inverse 
## 2-cacheSolve computes the inverse of the special matrix returned by the above function. 
## If the inverse has already been calculated, then it just retrieve from the cache

## this function make a cache of the matrix generated by the below function

makeCacheMatrix <- function(x = matrix()) {   ## this function take one argument - initiated as an empty matrix
  m<-NULL                                     
  set<-function(y){                           ## sub-function take an argument "y"
  x<<-y                                       ## special assignment to X    

}
get<-function() x
setmatrix<-function(solve) m<<- solve
getmatrix<-function() m
list(set=set, get=get,
   setmatrix=setmatrix,
   getmatrix=getmatrix)
}



## Write a short comment describing this function

cacheSolve <- function(x=matrix(), ...) {       ## this function take a main arguement x - initiated as an empty matrix
    m<-x$getmatrix()                    
    if(!is.null(m)){                            ## if m is NULL --> displace "getting cahced data" then
      message("getting cached data")            ##  return m obtain from the above function
      return(m)
    }
    matrix<-x$get()
    m<-solve(matrix, ...)                       ## apply solve to the given matrix and assign to m
    x$setmatrix(m)                              ## apply setmatrix function defined above on m and assign it to x
    m
}
